export const countryToAlpha2: { [key: string]: string } = {
  'France': 'FR',
  'Allemagne': 'DE',
  'Royaume-Uni': 'GB',
  'Espagne': 'ES',
  'Italie': 'IT',
  'Pays-Bas': 'NL',
  'Belgique': 'BE',
  'Suisse': 'CH',
  'Portugal': 'PT',
  'Suède': 'SE',
  'Norvège': 'NO',
  'Danemark': 'DK',
  'Finlande': 'FI',
  'Autriche': 'AT',
  'Irlande': 'IE',
  'Pologne': 'PL',
  'Grèce': 'GR',
  'République Tchèque': 'CZ',
  'Hongrie': 'HU',
  'Roumanie': 'RO',
  'Bulgarie': 'BG',
  'Croatie': 'HR',
  'Slovaquie': 'SK',
  'Slovénie': 'SI',
  'Estonie': 'EE',
  'Lettonie': 'LV',
  'Lituanie': 'LT',
  'Luxembourg': 'LU',
  'Malte': 'MT',
  'Chypre': 'CY',
  'États-Unis': 'US',
  'Canada': 'CA',
  'Mexique': 'MX',
  'Brésil': 'BR',
  'Argentine': 'AR',
  'Colombie': 'CO',
  'Pérou': 'PE',
  'Venezuela': 'VE',
  'Chili': 'CL',
  'Équateur': 'EC',
  'Bolivie': 'BO',
  'Paraguay': 'PY',
  'Uruguay': 'UY',
  'Guyane': 'GY',
  'Suriname': 'SR',
  'Chine': 'CN',
  'Japon': 'JP',
  'Inde': 'IN',
  'Corée du Sud': 'KR',
  'Indonésie': 'ID',
  'Thaïlande': 'TH',
  'Vietnam': 'VN',
  'Malaisie': 'MY',
  'Philippines': 'PH',
  'Singapour': 'SG',
  'Taïwan': 'TW',
  'Hong Kong': 'HK',
  'Macao': 'MO',
  'Pakistan': 'PK',
  'Bangladesh': 'BD',
  'Sri Lanka': 'LK',
  'Népal': 'NP',
  'Cambodge': 'KH',
  'Laos': 'LA',
  'Myanmar': 'MM',
  'Mongolie': 'MN',
  'Afrique du Sud': 'ZA',
  'Égypte': 'EG',
  'Nigeria': 'NG',
  'Kenya': 'KE',
  'Maroc': 'MA',
  'Algérie': 'DZ',
  'Tunisie': 'TN',
  'Ghana': 'GH',
  'Sénégal': 'SN',
  'Côte d\'Ivoire': 'CI',
  'Cameroun': 'CM',
  'Tanzanie': 'TZ',
  'Ouganda': 'UG',
  'Éthiopie': 'ET',
  'Rwanda': 'RW',
  'Maurice': 'MU',
  'Seychelles': 'SC',
  'Australie': 'AU',
  'Nouvelle-Zélande': 'NZ',
  'Fidji': 'FJ',
  'Papouasie-Nouvelle-Guinée': 'PG',
  'Samoa': 'WS',
  'Tonga': 'TO',
  'Vanuatu': 'VU'
};

export const alpha2ToCountry: { [key: string]: string } = Object.entries(countryToAlpha2).reduce(
  (acc, [country, code]) => ({ ...acc, [code]: country }),
  {}
);

export function convertToAlpha2(countries: string[]): string[] {
  return countries.map(country => countryToAlpha2[country] || country);
}

export function convertToCountryNames(codes: string[]): string[] {
  return codes.map(code => alpha2ToCountry[code] || code);
} 